webphp:
  build: php/.
  ports:
    - "9000:9000"
  volumes:
    - .:/Code/taurus
  links:
    - cache:cache
    - db:db
    - es:localhost

cache:
   image: redis
   ports:
    - "6379:6379"
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: chuantaiyidev
    MYSQL_USER: cty
    MYSQL_PASSWORD: chuantaiyidev
    MYSQL_DATABASE: taurus
es:
  build: ES/.
  ports:
    - "9200:9200"
    - "9300:9300"
server:
    build: nginx/.
    ports:
      - "80:80"
      - "443:443"
    links:
    - webphp:taurus  
    volumes_from:
      - webphp:rw

    
